### ISSUE TITLE
log

### ISSUE THREAD

**Issue by geagea1** [Rillke/GlobalReplace#1]
As I mentioned in https://commons.wikimedia.org/wiki/Commons:Bureaucrats%27_noticeboard/Archive_4#Commons:GlobalReplace there is no log and there is no records of replacements. If it is possible to add a log it will be grate.

Gia
User:Geagea

**Comment by maflcko** [comment]
How would the log look like?

Just appending for to https://commons.wikimedia.org/wiki/Commons:GlobalReplace/Log something like $File1 -> $File2 by $User

**Comment by Rillke** [comment]
Perhaps make a subpage on each user's namespace who makes use of the tool and auto-categorize them. Otherwise the single log page will possibly grow too quickly.

**Comment by maflcko** [comment]
Sounds better, and then also separate pages for each week/month?

**Comment by geagea1** [comment]
We have also 
https://commons.wikimedia.org/wiki/Commons:GlobalReplace/Sign-in

**Comment by revi** [comment]
On 2015년 6월 15일 오후 5시 31분 56초 GMT+09:00, MarcoFalke notifications@github.com wrote:

> Sounds better, and then also separate pages for each week/month?

How about [[User:{{USERNAME}}/GlobalReplace/Log/YYYY-MM]]?

## 

Yongmin Hong [Revi]
https://www.revi.pe.kr

**Comment by maflcko** [comment]
If it is ok like this, I will merge the dev-branch.

https://commons.wikimedia.org/w/index.php?title=User:McTrash1/GlobalReplaceLog/2015/06&action=history

**Comment by revi** [comment]
Looks good to me.

**Comment by revi** [comment]
When you merge #5, this will be autoclosed (if you put 'fixes #5' in commit message, it triggers github autoclose) so you do not need to close them manually.

And even if it doesn't trigger, you should leave issue open until it is in master.

**Comment by revi** [comment]
After all, bug is not fixed until it is in master branch.

**Comment by maflcko** [comment]
I am aware of that, but usually I forget to include the issue number when I type the commit message. I will try to keep that in mind, though.
