### ISSUE TITLE
Outsource library

### ISSUE THREAD

**Issue by Rillke** [Rillke/GlobalReplace#15]
I think it could be useful for building java tools interacting with the wiki anyway, and since it is used in Up!, too, this should be a separate repository (a sub-module in terms of git).

**Comment by Rillke** [comment]
And we might restore the some of Fastily's command line tools then. Some might come in handy.

**Comment by fastily** [comment]
the core library, jwiki, is [here](https://github.com/fastily/jwiki)

and if you're interested the command line tools I've written for Commons, you can see them [here](https://github.com/fastily/ctools/tree/junkyard)

**Comment by maflcko** [comment]
@Rillke I think this can be closed?

**Comment by Rillke** [comment]
We have a jar file now in our repo?

**Comment by fastily** [comment]
Yes, I explained my reasoning for this [here](https://github.com/Commonists/GlobalReplace/pull/23#issuecomment-178252543)

**Comment by maflcko** [comment]
Would it be possible to prepare jwiki for use with git subtrees?

**Comment by fastily** [comment]
Done, by @MarcoFalke in #39
