### ISSUE TITLE
Requesting Commit Access

### ISSUE THREAD

**Issue by fastily** [Rillke/GlobalReplace#18]
Hi, 

As the original author of this tool, I'm interested in helping out.  I wrote a new version awhile ago, v0.4, (with a completely redesigned UI as well as heavily improved/optimized business logic) which I'd like to merge with the current version.  My original source code not only contains detailed documentation (javadocs) but also resolves many, many issues with the v0.3 release of GR.

Cheers,
Fastily

**Comment by Rillke** [comment]
@JeanFred can you invite @fastily to the coder group? I think I can invite to the sysop group only.

@fastily If your change is huge, can you upload that into a fork or new branch so we can do a little review in advance? Thanks for changing your mind and welcome back.

**Comment by JeanFred** [comment]
@Rillke Done! @fastily now is member of @Commonists/software-coders who has write access.

**Comment by maflcko** [comment]
@fastily If you are not fluent in git: It may be easiest to checkout the inial commit of GR ( b5a53091a531356075b94d4fa688c17409b9fa59 ) branch or fork it, then apply your changes and commit. Afterward do a rebase on master (or pull master). Finally create a pull request. If you need help with solving merge conflicts or any of the steps, just let us know.

**Comment by fastily** [comment]
@MarcoFalke I've been using git for 5 years and counting 😀
I reviewed the code in this repo and didn't realize it was so far behind my version.  Both my [core](https://github.com/fastily/jwiki) and program itself have undergone hundreds of changes, up to the point where I'm not even sure a merge would make sense.  I'll look into this further over the weekend if I have time.

**Comment by Rillke** [comment]
You could merge our changes on top of yours if they make sense.

**Comment by maflcko** [comment]
Jup, just cherry-pick my non-refactor changes.

**Comment by maflcko** [comment]
Maybe even better: Upload your code and I will cherry-pick the relevant commits to your code?
