### ISSUE TITLE
not to be consider as a bot edit

### ISSUE THREAD

**Issue by geagea1** [Rillke/GlobalReplace#2]
When the tool make  replacement it is important that this edit will not consider as a bot edit. Because some wiki users seeing there watchlist with "hide bots". But this is not bot edit!

Gia
User:Geagea

**Comment by maflcko** [comment]
Keep in mind, only users with the bot permission can tag edits as bot edit.

**Comment by Rillke** [comment]
Are we actually setting the bot bit on `action=edit` somewhere?

**Comment by geagea1** [comment]
That's remind me. Can we limit the usage to filemovers, image reviewer and admins?

**Comment by maflcko** [comment]
What limit? ratelimit or files/day?

**Comment by revi** [comment]
I prefer the access limit like AWB, like CheckPage to check permission.

I suggest to close this issue as INVALID since you cannot tag your edit as bot unless you have 'bot' flag on your account on editing wikis. (Access restriction should be filed as a new bug).

**Comment by revi** [comment]
@Rillke @MarcoFalke See above comment, please?
@geagea1 Unless you have bot flag on the wiki you're editing on (e.g. Commons / enwiki/ kowiki) it will show up as normal edit. If user has bot flag on wiki and misuse his bot permissions, it will be dealt appropriately by the community, not by developers.

**Comment by geagea1** [comment]
Is it possible then to tag all replacements as not done by bot, no matter who is processing it (user with bot flag or without), it would be great.

**Comment by Steinsplitter** [comment]
Whitelist like AWB sounds reasonable.  But there is no protection at all, you never know is someone else is writing a tool without restrictions.

**Comment by maflcko** [comment]
@Rillke @geagea1  Afais we are not setting the bot bit anywhere, so I will close this issue.

@revi To gain permission, one has to sign up to use the tool. see pull request #3
