### ISSUE TITLE
Replace don't work on spanish wiki

### ISSUE THREAD

**Issue by wilfredor** [Rillke/GlobalReplace#21]
GlobalReplace show "Done!", howeve, I can't replace any file at spanish wikipedia

**Comment by maflcko** [comment]
Can you replace file usage at other wikis?

**Comment by wilfredor** [comment]
Yes, I can do it with my user, in superprotect pages or whatever without GlobalReplace tool

**Comment by maflcko** [comment]
@wilfredor Can you still reproduce with the latest version? If so, please add detailed steps to reproduce so I can have a look.

**Comment by maflcko** [comment]
It looks like GR 0.6.3 does not work at all. At any wiki... I am not sure if the [original version](https://github.com/Commonists/GlobalReplace/commit/1e115d71324706ae4aa7a5e553bf11b0707db5b7#diff-5017d2ce1334f2e90cc65adbe7612821R116) is affected as well.
