### ISSUE TITLE
Cannot login (with special characters in password)

### ISSUE THREAD

**Issue by Rillke** [Rillke/GlobalReplace#22]
> When I try to login to GlobalReplace, it said my user/password is not recognized. Does this application supports the accented e in my username? If not, do I need to change my username, or can you fix it? I would like to use this to help clear the backlog at [[User talk:CommonsDelinker/commands]]. Thanks
> 
> Okay, it seems I solved it. The password is the problem. My password contains special characters, capitalized letters, and numbers. That seems to be the cause of the problem. I changed my password and my login to GR is now successful. 

[source](https://commons.wikimedia.org/w/index.php?title=Commons_talk%3AGlobalReplace&type=revision&diff=183594195&oldid=181968126)

**Comment by geagea1** [comment]
I had similar problem as my password contain Hebrew letter. The Hebrew is
not available in the password line so I wrote it elsewhere and copy paste
it.

Gia
User:Geagea

2016-01-03 8:52 GMT+02:00 Rainer Rillke notifications@github.com:

**Comment by Steinsplitter** [comment]
same issue here.

**Comment by maflcko** [comment]
Looks like this only happens on Windows...

**Comment by fastily** [comment]
It sounds like POST parameters aren't being properly URLEncoded.  The version of [jwiki](https://github.com/fastily/jwiki) in this repo is very outdated; I am pretty sure that the newest release does not have this issue.

**Comment by fastily** [comment]
If nobody is working on this bug, then I can fix it sometime next week

**Comment by maflcko** [comment]
You mean updating to the new version of jwiki? I am happy to review the pull once created.

**Comment by fastily** [comment]
Done, see #23

**Comment by Rillke** [comment]
Can someone confirm that this is fixed now so that we can close this issue?

**Comment by maflcko** [comment]
@geagea1 Can you still reproduce the issue?

**Comment by Steinsplitter** [comment]
Works for me now. :smile:
