### ISSUE TITLE
Problematic Minimum Versions

### ISSUE THREAD

**Issue by revi** [Rillke/GlobalReplace#32]
Your [latest release according to github](https://github.com/Commonists/GlobalReplace/releases/latest) is v0.6.4 and Commons [minimum version](https://commons.wikimedia.org/wiki/Commons:GlobalReplace/MinimumVersion) is is v0.6.5. Please release the new version or revert the edit. Thanks.

**Comment by maflcko** [comment]
Hi, there are reports that previous versions are not functioning correctly or not at all. As a precaution, we have disabled GlobalReplace for the time being.

Unfortunately there is no ETA of GlobalReplace v0.6.5.

**Comment by revi** [comment]
Then please state it in the wiki page. :D
